import type { SiteLocale } from '@/platform/site'
const labels = {
  zh: {
    home: '首页',
    products: '产品中心',
    news: '新闻资讯',
    cases: '案例中心',
    blog: '技术博客',
    about: '关于我们',
    contact: '联系我们',
    faqs: '常见问题',
    menu: '菜单',
    more: '查看全部',
    detail: '查看详情',
    empty: '暂无已发布内容',
    strength: '企业实力',
    quote: '提交询盘',
    specs: '技术参数',
    description: '产品介绍',
    download: '下载规格书',
    all: '全部分类',
    name: '姓名',
    company: '公司',
    email: '邮箱',
    phone: '电话 / WhatsApp',
    country: '国家',
    message: '需求说明',
    product: '意向产品',
    send: '提交询盘',
    sending: '提交中…',
    sent: '询盘已提交。',
    error: '提交失败，请稍后重试。',
    preview: '模板预览，不会更换当前模板',
    skip: '跳转到内容',
    links: '快速导航',
    pause: '暂停轮播',
    play: '播放轮播',
    previous: '上一张',
    next: '下一张',
    previewForm: '预览模式下不发送询盘。',
    certificate: '证书资质',
  },
  en: {
    home: 'Home',
    products: 'Products',
    news: 'News',
    cases: 'Case Studies',
    blog: 'Blog',
    about: 'About Us',
    contact: 'Contact',
    faqs: 'FAQ',
    menu: 'Menu',
    more: 'View All',
    detail: 'View Details',
    empty: 'No published content yet',
    strength: 'Our Capabilities',
    quote: 'Request a Quote',
    specs: 'Specifications',
    description: 'Product Overview',
    download: 'Download Datasheet',
    all: 'All Categories',
    name: 'Name',
    company: 'Company',
    email: 'Email',
    phone: 'Phone / WhatsApp',
    country: 'Country',
    message: 'Requirements',
    product: 'Product',
    send: 'Send Inquiry',
    sending: 'Sending…',
    sent: 'Your inquiry has been sent.',
    error: 'Could not send. Please try again.',
    preview: 'Template preview; your active template is unchanged',
    skip: 'Skip to Content',
    links: 'Quick Links',
    pause: 'Pause Slideshow',
    play: 'Play Slideshow',
    previous: 'Previous',
    next: 'Next',
    previewForm: 'Inquiries are disabled in preview.',
    certificate: 'Certificates',
  },
  ru: {
    home: 'Главная',
    products: 'Продукция',
    news: 'Новости',
    cases: 'Проекты',
    blog: 'Блог',
    about: 'О компании',
    contact: 'Контакты',
    faqs: 'Частые вопросы',
    menu: 'Меню',
    more: 'Смотреть все',
    detail: 'Подробнее',
    empty: 'Опубликованных материалов пока нет',
    strength: 'Наши возможности',
    quote: 'Запросить цену',
    specs: 'Технические параметры',
    description: 'Описание продукта',
    download: 'Скачать спецификацию',
    all: 'Все категории',
    name: 'Имя',
    company: 'Компания',
    email: 'Эл. почта',
    phone: 'Телефон / WhatsApp',
    country: 'Страна',
    message: 'Требования',
    product: 'Продукт',
    send: 'Отправить запрос',
    sending: 'Отправка…',
    sent: 'Запрос отправлен.',
    error: 'Ошибка отправки. Повторите попытку.',
    preview: 'Предпросмотр; текущий шаблон не изменён',
    skip: 'Перейти к содержимому',
    links: 'Быстрые ссылки',
    pause: 'Пауза',
    play: 'Продолжить',
    previous: 'Назад',
    next: 'Вперёд',
    previewForm: 'Отправка запросов в предпросмотре отключена.',
    certificate: 'Сертификаты',
  },
  id: {
    home: 'Beranda',
    products: 'Produk',
    news: 'Berita',
    cases: 'Studi Kasus',
    blog: 'Blog',
    about: 'Tentang Kami',
    contact: 'Kontak',
    faqs: 'Pertanyaan Umum',
    menu: 'Menu',
    more: 'Lihat Semua',
    detail: 'Lihat Detail',
    empty: 'Belum ada konten yang diterbitkan',
    strength: 'Kemampuan Kami',
    quote: 'Minta Penawaran',
    specs: 'Spesifikasi',
    description: 'Deskripsi Produk',
    download: 'Unduh Spesifikasi',
    all: 'Semua Kategori',
    name: 'Nama',
    company: 'Perusahaan',
    email: 'Email',
    phone: 'Telepon / WhatsApp',
    country: 'Negara',
    message: 'Kebutuhan',
    product: 'Produk',
    send: 'Kirim Pertanyaan',
    sending: 'Mengirim…',
    sent: 'Pertanyaan telah dikirim.',
    error: 'Gagal mengirim. Silakan coba lagi.',
    preview: 'Pratinjau templat; templat aktif tidak berubah',
    skip: 'Lewati ke Konten',
    links: 'Tautan Cepat',
    pause: 'Jeda',
    play: 'Putar',
    previous: 'Sebelumnya',
    next: 'Berikutnya',
    previewForm: 'Pengiriman dinonaktifkan dalam pratinjau.',
    certificate: 'Sertifikat',
  },
}
export const templateCopy = (locale: SiteLocale) => labels[locale]
