export const newTemplates = [
  {
    key: 'interior-575-v1',
    version: '1.0.0',
    schemaVersion: 1,
    reference: '575',
    referenceURL: 'http://zh.preview.default3.temp.o668.com/',
    name: '室内家居 · 575',
    industry: 'home-interior',
    tone: 'interior',
    primary: '#675747',
    accent: '#a47b54',
    description: '暖色家居画册：圆角横幅、留白图文、案例优先、编辑式资讯。',
    modules: ['intro', 'cases', 'products', 'strength', 'video', 'news', 'inquiry'],
  },
  {
    key: 'power-705-v1',
    version: '1.0.0',
    schemaVersion: 1,
    reference: '705',
    referenceURL: 'http://zh.preview.default2.temp.o668.com/',
    name: '电源设备 · 705',
    industry: 'power-equipment',
    tone: 'power',
    primary: '#17364e',
    accent: '#b74721',
    description: '设备企业官网：联系顶栏、企业介绍、实力横排、产品与视频。',
    modules: ['intro', 'strength', 'products', 'video', 'cases', 'news', 'inquiry'],
  },
  {
    key: 'autoparts-571-v1',
    version: '1.0.0',
    schemaVersion: 1,
    reference: '571',
    referenceURL: 'http://zh.preview.k571.temp.o668.com/',
    name: '汽配五金 · 571',
    industry: 'auto-parts',
    tone: 'autoparts',
    primary: '#202a39',
    accent: '#b83c25',
    description: '紧凑五金目录：多层页头、独立导航、分类侧栏、密集产品展示。',
    modules: ['video', 'intro', 'cases', 'products', 'strength', 'news', 'inquiry'],
  },
  {
    key: 'machinery-710-v1',
    version: '1.0.0',
    schemaVersion: 1,
    reference: '710',
    referenceURL: 'http://zh.preview.k710.temp.o668.com/',
    name: '通用机械 · 710',
    industry: 'machinery',
    tone: 'machinery',
    primary: '#18372f',
    accent: '#527461',
    description: '机械设备展示：深色导航、产品切换展台、技术参数与下载。',
    modules: ['products', 'strength', 'intro', 'cases', 'video', 'news', 'inquiry'],
  },
  {
    key: 'solar-test-655-v1',
    version: '1.0.0',
    schemaVersion: 1,
    reference: '655',
    referenceURL: 'http://zh.preview.k655.temp.o668.com/',
    name: '光伏测试 · 655',
    industry: 'renewable-energy',
    tone: 'solar',
    primary: '#075c80',
    accent: '#b94b14',
    description: '蓝色技术官网：四列产品、案例横向浏览、主次资讯与实力展示。',
    modules: ['products', 'cases', 'news', 'strength', 'intro', 'video', 'inquiry'],
  },
] as const
export type NewTemplate = (typeof newTemplates)[number]
export const getNewTemplate = (key?: string | null) => newTemplates.find((item) => item.key === key)
