name: novasite-platform

services:
  postgres:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: novasite
      POSTGRES_USER: novasite
      POSTGRES_PASSWORD: novasite
    ports:
      - "5433:5432"
    volumes:
      - novasite_postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U novasite -d novasite"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - novasite_redis:/data

  minio:
    image: minio/minio:latest
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: novasite
      MINIO_ROOT_PASSWORD: novasite-local-secret
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - novasite_minio:/data

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  novasite_postgres:
  novasite_redis:
  novasite_minio:
